groups:
  - name: master
    jobs:
      - test-pull-request
      - test-master
      - ship-master
      - integration-master
      - patch
      - minor
      - major
      - rc

  - name: production
    jobs:
      - merge-master-to-production
      - test-production
      - ship-production

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: repo-master
    type: git
    source:
      uri: {{github-repo-uri}}
      branch: master
      private_key: {{github-private-key}}

  - name: repo-production
    type: git
    source:
      uri: {{github-repo-uri}}
      branch: production
      private_key: {{github-private-key}}

  - name: pull-request
    type: pull-request
    source:
      access_token: {{github-access-token}}
      private_key: {{github-private-key}}
      repo: {{github-repo-name}}
      every: true

  - name: version
    type: semver
    source:
      driver: git
      uri: {{github-repo-uri}}
      branch: version/master
      private_key: {{github-private-key}}
      file: version
      initial_version: {{initial-version}}

  - name: production-version
    type: semver
    source:
      driver: git
      uri: {{github-repo-uri}}
      branch: version/production
      private_key: {{github-private-key}}
      file: version
      initial_version: {{initial-version}}

jobs:

  - name: test-pr
    plan:
    - get: pr
      resource: pull-request
      version: every
      trigger: true
    - put: pull-request
      params:
        path: pr
        status: pending
    - task: test-pull-request
      file: repo/ci/tasks/unit.yml
      input_mapping: { repo: pr }
      on_success:
        put: pull-request
        params:
          path: pr
          status: success
      on_failure:
        put: pull-request
        params:
          path: pr
          status: failure

  - name: test-master
    plan:
      - get: master
        resource: repo-master
        trigger: true
      - task: unit
        file: repo/ci/tasks/unit.yml
        input_mapping: { repo: master }

  - name: integrate-master
    serial: true
    plan:
      - aggregate:
        - get: master
          resource: repo-master
          trigger: true
          passed: [ test-master ]
      - task: integration-test
        file: repo/ci/tasks/integration.yml
        input_mapping: {repo: master}

  - name: version-master
    serial: true
    serial_groups: [ update-version ]
    plan:
      - aggregate:
        - get: master
          resource: repo-master
          trigger: true
          passed: [ integrate-master]
        - get: version
      - put: version
        params: { pre: rc }

  - name: ship-master
    serial: true
    plan:
      - aggregate:
        - get: master
          resource: repo-master
          trigger: true
          passed: [ version-master ]
        - get: version
          passed: [ version-master ]
      - task: ship-develop
        file: repo/ci/tasks/shipit.yml
        input_mapping: { repo: master }
        output_mapping: { repo: master }
      - put: master
        resource: repo-master

  - name: merge-master-to-production
    serial: true
    plan:
      - aggregate:
        - get: master
          resource: repo-master
          passed: [ ship-master ]
        - get: production
          resource: repo-production
      - task: merge-master-to-production
        file: master/ci/tasks/merge-branch.yml
        input_mapping: { from: master, to: production }
        output_mapping: { out: next-production }
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
          NO_FF: true
      - put: production
        resource: repo-production
        params:
          repository: next-production

  - name: test-production
    serial: true
    disable_manual_trigger: true
    plan:
      - get: production
        resource: repo-production
        # comment out next line for support hotfix
        passed: [ merge-master-to-production ]
        trigger: true
      - task: unit-on-production
        file: repo/ci/tasks/unit.yml
        input_mapping: { repo: production }

  - name: version-production
    serial: true
    plan:
      - aggregate:
        - get: production
          resource: repo-production
          passed: [ test-production ]
          trigger: true
        - get: version
          params: { bump: final }
      - put: production-version
        params: { file: version/version }

  - name: tag-production
    serial: true
    disable_manual_trigger: true
    plan:
      - aggregate:
        - get: production
          resource: repo-production
          passed: [ version-production ]
          trigger: true
        - get: production-version
          passed: [ version-production ]
      - put: production
        resource: repo-production
        params:
          repository: production
          tag: production-version/version

  - name: ship-production
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: production
        resource: repo-production
        passed: [ tag-production ]
        trigger: true
      - get: production-version
        passed: [ tag-production ]
      - task: ship-production
        file: repo/ci/tasks/shipit.yml
        input_mapping: { repo: production, version: production-version }

  - name: start-next-version
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: production-version
        passed: [ ship-production ]
        trigger: true
      - put: version
        params: { file: production-version/version, bump: patch, pre: rc }


# semver control
  - name: patch
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: version
      - put: version
        params: { bump: patch, pre: rc }
      - get: version
        parms: { pre: beta }

  - name: minor
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: version
      - put: version
        params: { bump: minor, pre: rc }

  - name: major
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: version
      - put: version
        params: { bump: major, pre: rc }

  - name: rc
    serial: true
    serial_groups: [ update-version ]
    plan:
      - get: version
      - put: version
        parms: { pre: rc }
